site_name: BD103 Python Package
site_author: BD103
site_description: Python Package on PyPI
repo_name: BD103/Package
repo_url: https://github.com/BD103/Package/
copyright: Copyright &copy; 2020 BD103
docs_dir: src
site_dir: docs
nav:
    - Home: index.md
    - Color: color.md
theme:
    name: material
    palette:
      scheme: slate
      primary: blue
      accent: light blue
    language: en
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
plugins:
    - mkdocstrings
extra:
    social:
      - icon: octicons/code-review-16
        link: https://repl.it/@BD103
      - icon: fontawesome/brands/github
        link: https://github.com/BD103