name: Lint

on:
  push:
    branches:
      - master

jobs:
  lint:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: [3.7]

     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v2
       - uses: jpetrucciani/black-check@master
         with:
           path: bd103
