name: Test
on: 
  push:
    branches: 
      - main
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: ${{ matrix.os }} - ${{ matrix.python-version }} Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get dependencies
      run: pip install -U pytest
    - name: Test
      run: pytest
