name: Lint

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9", "3.10"]
    
    defaults:
      run:
        shell: bash
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
      
      - name: Install Dependencies
        run: poetry install -E ext
      
      - name: Pytest
        run: poetry run pytest
